### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by ghost**
## Changes
Updated plugin.yml and added SlimeCustomizer as softdepend

## Related Issues
Fixes relics not being able to use SlimeCustomizer items by loading this addon after SlimeCustomizer

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by FN-FAL113** [comment]
I'll take a look at this soon enough, apologies though still busy irl

have u tried testing this yourself?

**Comment by ghost** [comment]
Wait I will build the jar and check if it works

**Comment by ghost** [comment]
Yes it does work 
image
image
But there is one error
image

**Comment by FN-FAL113** [comment]
you soft depend on slime customizer

**Pull request closed without merging**
