### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by alexey-va**
## Changes
- Added translation via configuration
- Broken pom and main class a bit (could not compile with dough) so it needs a little tweaking

Not very clean yet

## Checklist

- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.

### CODE REVIEW

**Comment by alexey-va** [comment]
the way you inject sources and trades in lore is a problem though. I personally added config option to disable injecting them at all. Also one can add something like this in translation:
```yaml
drops-on: "Drops on:"
possible-piglin-reward: "Possible Piglin reward:"
```
then all thats left is to translate sources and rewards

**Comment by alexey-va** [comment]
More or less ready I think. Also added some useful config options

**Comment by FN-FAL113** [comment]
big pr, could have been segmented nonetheless I appreciate your effort and time for doing the feature and chores. I will check this out from time to time as I am currently busy with life.

**Comment by alexey-va** [comment]
Broke it into 3 steps:
- Translating items
- Translating messages
- Translating sources/trades

Didn't take much time though, I just wrote proxy classes so that when you create items or use sources/trades they are appended to translation config file. Took like 1-2 hours total. Most lines don't have any logic, only main class needs rework on your part (I broke dough integration cuz couldn't compile with it)

**Comment by FN-FAL113** [comment]
> Broke it into 3 steps:
> 
> * Translating items
> * Translating messages
> * Translating sources/trades
> 
> Didn't take much time though, I just wrote proxy classes so that when you create items or use sources/trades they are appended to translation config file. Took like 1-2 hours total. Most lines don't have any logic, only main class needs rework on your part (I broke dough integration cuz couldn't compile with it)

can you revert back to using dough common and dough updater but only updating the commit hash using recent successful build/s from jitpack [dough jitpack](https://jitpack.io/#baked-libs/dough). If you're using intellij you can try clearing and invaliding cache. For vscode it will ask to update the classpath. Reason why I use updater and common as I do not use the whole dough-api and at the same time to lessen uber jar size.

**Comment by alexey-va** [comment]
updating to latest build from jitpack solved the issue

**Comment by FN-FAL113** [comment]
There's just small conflict on this caused by the newly merged pr.

**Pull request closed without merging**
